"""
Drawing class
Each drawing is an object of this class
It contains the date, index, status, and the file name.
The file name is the date and index.
The status is the status of the drawing.
The status is "pending" by default.
The status can be "pending", "finished" or "paused".
"finished" status is only determined if the drawing is finished and this status can be set by the algorithm.
"paused" is set by the user if they clicked on the [pause] button in the Queue GUI window.
"""
from datetime import datetime
import os
from .paths import PATHS

FILE_PATH = os.path.dirname(os.path.abspath(__file__))
# APP_DIR = os.path.dirname(FILE_PATH)
# DATA_DIR = os.path.join(APP_DIR, "data")
# SVG_OUTPUT_DIR = os.path.join(DATA_DIR, "svg_inputs_outputs", "svg_output")
# PREVIEW_DIR = os.path.join(DATA_DIR, "svg_window_preview")

DATA_DIR = PATHS["DATA_DIR"]
SVG_OUTPUT_DIR = PATHS["SVG_OUTPUT_DIR"]
PREVIEW_DIR = PATHS["SVG_WINDOW_PREVIEW_DIR"]

class Drawing:
    def __init__(self, status="pending", recreate_from_file=False, date=None, index=None, progress=None, paper_size=""):
        
        if recreate_from_file:
            if date is None or index is None:
                raise ValueError("date and index must be provided when recreating from file")
            else:
                self.date = date
                self.index = index
                self.status = status
                self.progress = progress
                self.paper_size = paper_size
            
        else:
            self.date = datetime.now().strftime("%d-%m-%Y")
            self.status = status
            self.index = self.set_index()
            self.progress = progress
            self.paper_size = paper_size

    def set_index(self):
        """Checks if indexes.txt already exists if not create it and add f"{date}_1",
        if it exists, and today is there read the highest index of today, increment it and add a new line,
        else, add a new line with f"{date}_1" """
        
        index = 1
        index_file = os.path.join(FILE_PATH, "indexes.txt")
        
        if os.path.exists(index_file): #Check if the index file exists
            with open(index_file, "r") as file:
                lines = file.readlines()
            
            # Find the highest index for today
            for line in lines:
                if line.startswith(self.date):
                    right = line.split("_")[1] # line = "dd-mm-yyyy_index:status" right = "index:status"
                    current_index = int(right.split(":")[0]) # Current index = "index"
                    if current_index >= index:
                        index = current_index + 1
            
        else: # If the index file does not exist, create it
            with open(index_file, "w") as file:
                file.write("# This file keeps track of indexes it is machine readable and can be used as a reference to keep track of how many drawings were generated in each day\n# DO NOT EDIT THIS FILE\n")
                index = 1
        self.index = index
        return index

    def get_status(self):
        return self.status
    
    def set_status(self, new_status):
        self.status = new_status
    
    def set_paper_size(self, new_paper_size):
        self.paper_size = new_paper_size
    
    def get_date(self):
        return self.date
    
    def get_index(self):
        return self.index
    
    def get_progress(self):
        return self.progress
    
    def set_progress(self, new_progress):
        self.progress = new_progress
    
    def get_file(self):
        # get the file from the date and index
        return f"{self.date}_{self.index}.svg"
    
    def get_preview_image(self):
        # get the preview image from the date and index
        return f"preview_{self.date}_{self.index}.png"
    
    def get_svg_path(self):
        # get the svg output path from the date and index
        return os.path.join(SVG_OUTPUT_DIR, self.get_file())
    
    def get_preview_path(self):
        # get the preview output path from the date and index
        return os.path.join(PREVIEW_DIR, self.get_preview_image())
    
    def get_gui_line(self):
        """
        Returns a string that contains the date, index, status, svg path, and preview path.
        This is used to display the drawing in the GUI.
        """
        return f"  {self.date}#{self.index} Status: {self.status} {self.paper_size}"
    
    def get_index_file_line(self):
        """
        Returns a string that contains the date, index, and status.
        This is used to write the drawing to the index file.
        """
        return f"{self.date}_{self.index}:{self.status}\n"
    
        
def test():
    drawing = Drawing()
    print(f"Date: {drawing.get_date()}")
    print(f"Index: {drawing.get_index()}")
    print(f"Status: {drawing.get_status()}")
    print(f"SVG Path: {drawing.get_svg_path()}")
    print(f"Preview Path: {drawing.get_preview_path()}")
    print(f"File Name: {drawing.get_file()}")
    print(f"Preview Image: {drawing.get_preview_image()}")

if __name__ == "__main__":
    test()
    # pass

    