"""
This is a Queue class that provides a simple interface for managing a queue of drawing tasks.
The Queue class is just a list with helper methods to add, remove, and check the status of tasks.
This Queue class is designed to work with a file that keeps track of the tasks and their statuses, in case the application needs to be restarted or the tasks need to be persisted.
# It also provides methods to update the status of tasks and retrieve tasks from the file.
"""
import os
from .drawing import Drawing

FILE_DIR = os.path.dirname(os.path.abspath(__file__))
INDEX_FILE = os.path.join(FILE_DIR, "indexes.txt")

class Queue:
    def __init__(self):
        self.queue = []

    def add_task(self, task):
        """
        Add a task to the queue.
        task: A drawing object
        """
        self.queue.append(task)
        self.update_file()  # Update the file after adding a new task
        
    def update_task(self, index, new_status):
        """
        Update the status of the front task in the queue.
        status: The new status of the task
        """
        if self.queue:
            self.queue[index].status = new_status
            self.update_file()  # Update the file after changing the status
    
    def update_file(self):
        """TODO: This method will export the current queue to a file."""
        os.remove(INDEX_FILE) if os.path.exists(INDEX_FILE) else None # Delete the file if it exists to avoid appending to it
        # Write the current queue to the file
        with open(INDEX_FILE, "w") as file:
            file.write("# This file keeps track of indexes it is machine readable and can be used as a reference to keep track of how many drawings were generated in each day\n# DO NOT EDIT THIS FILE\n")
            for task in self.queue:
                file.write(f"{task.date}_{task.index}:{task.status}-{task.paper_size}\n")

    def retrive_from_file(self):
        """TODO: This method will read each line in the file and populate the queue."""
        if not os.path.exists(INDEX_FILE):
            print("Index file does not exist. No tasks to retrieve.")
            return
        with open(INDEX_FILE, "r") as file:
            lines = file.readlines()
        for line in lines:
            if line.startswith("#"):
                continue
            parts = line.strip().split(":")
            if len(parts) != 2:
                print(f"Invalid line format: {line.strip()}")
                continue
            date_index, status_paper = parts
            date, index = date_index.split("_")
            index = int(index)
            
            # Split status and paper_size
            if "-" in status_paper:
                status, paper_size = status_paper.split("-", 1)
            else:
                status = status_paper
                paper_size = None  # Default if no paper_size is specified
            
            # Initialize a Drawing object with the retrieved data
            drawing = Drawing(recreate_from_file=True, date=date, index=index, status=status, paper_size=paper_size)
            self.queue.append(drawing) # Populate the queue with Drawing objects
    
    def remove_task(self, index):
        """
        Remove a task from the queue by its index.
        index: The index of the task to remove
        """
        #TODO: Implement this method to remove a task from the queue. The two lines below are AI suggestions
        if 0 <= index < len(self.queue):
            del self.queue[index]
        self.update_file()
    
    def clear_queue(self):
        """
        Clear the queue.
        """
        self.queue = []
        if os.path.exists(INDEX_FILE):
            os.remove(INDEX_FILE)
            with open(INDEX_FILE, "w") as file:
                file.write("# This file keeps track of indexes it is machine readable and can bee used as a reference to keep track of how many drawings were generated in each day\n# DO NOT EDIT THIS FILE\n")